#!/usr/bin/bash

if [ "$#" != "1" ]; then
	echo "Usage: deploy <version-number>"
	exit 1
fi

BUCKET="edu.au.cc.image-gallery-config1"

aws s3 cp ec2-scripts/ec2-prod-$1.sh s3://${BUCKET}
aws s3 cp nginx/nginx.conf s3://${BUCKET}/nginx/nginx.conf
aws s3 cp nginx/default.d/image_gallery.conf s3://${BUCKET}/nginx/default.d/image_gallery.conf

