---
- hosts: localhost
  gather_facts: no
  
  vars:
    
    vpc_name: ig-mod5-vpc
    vpc_cidr: 10.5.0.0/16
    vpc_region: us-east-1
    
  tasks:
    - name: Create VPC
      ec2_vpc_net:
        name: "{{ vpc_name }}"
        cidr_block: "{{ vpc_cidr }}"
        tags:
          Module: 5
        region: "{{ vpc_region }}"
        state: present
        multi_ok: no
      register: vpc
