---
- hosts: localhost
  gather_facts: no
  
  vars:
    
    database_name = image_gallery
    IAM_user = arn:aws:iam::290659162154:user/Administrator
    runtime =  'python 3.8'
    s3_bucket = edu.au.cc.image-gallery-config-mod5
    s3_key = ec2-prod-latest.sh
  
  tasks:
    - name: sm-ig-postgres
      lambda:
        description: Secrets manager for 'postgres' user
        tags:
          Module: 5
        environment_variables:
          database_name: "{{ database_name }}"
        role: "{{ IAM_user }}"
        runtime: "{{ runtime }}"
        #s3_bucket: "{{ s3_bucket }}"
        #s3_key: "{{ s3_key }}"
        #vpc_subnet_ids:
          #- "{{ private_subnet_1.subnet.id }}"
          #- "{{ private_subnet_2.subnet.id }}"
        #vpc_subnet_groups:
          #- "{{ ig-postgres-tag }}"
          #- "{{ ig-secretsmanager-tag }}"
        state: present
      register: postgres-lambda 

    - name: sm-ig-image_gallery
      lambda:
        description: Secrets manager for 'image_gallery' user
        tags:
          Module: 5
        environment_variables:
          database_name: "{{ database_name }}"
        role: "{{ IAM_user }}"
        runtime: "{{ runtime }}"
        #s3_bucket: "{{ s3_bucket }}"
        #s3_key: "{{ s3_key }}"
        #vpc_subnet_ids:
          #- "{{ private_subnet_1.subnet.id }}"
          #- "{{ private_subnet_2.subnet.id }}"
        #vpc_subnet_groups:
          #- "{{ ig-postgres-tag }}"
          #- "{{ ig-secretsmanager-tag }}"
        state: present
      register: image-gallery-lambda
