---
- hosts: localhost
  gather_facts: no
  
  vars:

    region: us-east-1
    az1: us-east-1e
    az2: us-east-1d

    pub_sn1_cidr: 10.5.1.0/24
    pub_sn2_cidr: 10.5.2.0/24
    priv_sn1_cidr: 10.5.3.0/24
    priv_sn2_cidr: 10.5.4.0/24
    
    pub_sn1_name: ig-pub-sn1
    pub_sn2_name: ig-pub-sn2
    priv_sn1_name: ig-priv-sn1
    priv_sn2_name: ig-priv-sn2  

  
  tasks:

    - name: Create public VPC subnet1
      ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ region }}"
        az: "{{ az1 }}"
        tags:
          Name: "{{ pub_sn1_name }}"
          Module: 5
        cidr: "{{ pub_sn1_cidr }}"
        state: present
      register: public_subnet_1

    - name: Create public VPC subnet2
      ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ region }}"
        az: "{{ az2 }}"
        tags:
          Name: "{{ pub_sn2_name }}"
          Module: 5
        cidr: "{{ pub_sn2_cidr }}"
        state: present
      register: public_subnet_2

    - name: Create private VPC subnet1
      ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ region }}"
        az: "{{ az1 }}"
        tags:
          Name: "{{ priv_sn1_name }}"
          Module: 5
        cidr: "{{ priv_sn1_cidr }}"
        state: present
      register: private_subnet_1

    - name: Create private VPC subnet2
      ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ region }}"
        az: "{{ az2 }}"
        tags:
          Name: "{{ priv_sn2_name}}"
          Module: 5
        cidr: "{{ priv_sn2_cidr }}"
        state: present
      register: private_subnet_2
