---
- hosts: localhost
  gather_facts: no
  
  vars:

    record: tnguyenken.net  
  
  tasks:
  - name: Write record for tnguyenken.net 
    route53:
      command: create
      zone: "{{ record }}"
      record: "{{ record }}" # intentionally same name as zone for SSL verification
      overwrite: yes
      type: A
      value: "{{ ig_nlb.dns_name }}"
      alias: yes
      alias_hosted_zone_id: "{{ ig_nlb.canonical_hosted_zone_id }}"
    register: cert
